package com.web.Agrifood.mapper;

import com.web.Agrifood.model.Cart;
import com.web.Agrifood.model.CartExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CartMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	long countByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	int deleteByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	int insert(Cart row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	int insertSelective(Cart row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	List<Cart> selectByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	Cart selectByPrimaryKey(Integer id);
	
	// Cart mapper custom
	Cart selectByProductId(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Cart row, @Param("example") CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	int updateByExample(@Param("row") Cart row, @Param("example") CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	int updateByPrimaryKeySelective(Cart row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	int updateByPrimaryKey(Cart row);
}