package com.web.Agrifood.mapper;

import com.web.Agrifood.model.Category;
import com.web.Agrifood.model.CategoryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sat Jul 16 08:46:16 ICT 2022
	 */
	long countByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sat Jul 16 08:46:16 ICT 2022
	 */
	int deleteByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sat Jul 16 08:46:16 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sat Jul 16 08:46:16 ICT 2022
	 */
	int insert(Category row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sat Jul 16 08:46:16 ICT 2022
	 */
	int insertSelective(Category row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sat Jul 16 08:46:16 ICT 2022
	 */
	List<Category> selectByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sat Jul 16 08:46:16 ICT 2022
	 */
	Category selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sat Jul 16 08:46:16 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Category row, @Param("example") CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sat Jul 16 08:46:16 ICT 2022
	 */
	int updateByExample(@Param("row") Category row, @Param("example") CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sat Jul 16 08:46:16 ICT 2022
	 */
	int updateByPrimaryKeySelective(Category row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sat Jul 16 08:46:16 ICT 2022
	 */
	int updateByPrimaryKey(Category row);
}