package com.web.Agrifood.mapper;

import com.web.Agrifood.model.Feedback;
import com.web.Agrifood.model.FeedbackExample;
import com.web.Agrifood.model.FeedbackKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    long countByExample(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int deleteByExample(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int deleteByPrimaryKey(FeedbackKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int insert(Feedback row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int insertSelective(Feedback row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    List<Feedback> selectByExampleWithBLOBs(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    List<Feedback> selectByExample(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    Feedback selectByPrimaryKey(FeedbackKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int updateByExampleSelective(@Param("row") Feedback row, @Param("example") FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int updateByExampleWithBLOBs(@Param("row") Feedback row, @Param("example") FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int updateByExample(@Param("row") Feedback row, @Param("example") FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int updateByPrimaryKeySelective(Feedback row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int updateByPrimaryKeyWithBLOBs(Feedback row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int updateByPrimaryKey(Feedback row);
}