package com.web.Agrifood.mapper;

import com.web.Agrifood.model.OrderItem;
import com.web.Agrifood.model.OrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    long countByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int deleteByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int deleteByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int insert(OrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int insertSelective(OrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    List<OrderItem> selectByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    OrderItem selectByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int updateByExampleSelective(@Param("row") OrderItem row, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int updateByExample(@Param("row") OrderItem row, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int updateByPrimaryKeySelective(OrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int updateByPrimaryKey(OrderItem row);
}