package com.web.Agrifood.mapper;

import com.web.Agrifood.model.OrderStatus;
import com.web.Agrifood.model.OrderStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    long countByExample(OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int deleteByExample(OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int deleteByPrimaryKey(Integer statusid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int insert(OrderStatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int insertSelective(OrderStatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    List<OrderStatus> selectByExample(OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    OrderStatus selectByPrimaryKey(Integer statusid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int updateByExampleSelective(@Param("row") OrderStatus row, @Param("example") OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int updateByExample(@Param("row") OrderStatus row, @Param("example") OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int updateByPrimaryKeySelective(OrderStatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    int updateByPrimaryKey(OrderStatus row);
}