package com.web.Agrifood.mapper;

import com.web.Agrifood.model.ProductImages;
import com.web.Agrifood.model.ProductImagesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ProductImagesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_images
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	long countByExample(ProductImagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_images
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	int deleteByExample(ProductImagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_images
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_images
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	int insert(ProductImages row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_images
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	int insertSelective(ProductImages row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_images
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	List<ProductImages> selectByExample(ProductImagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_images
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	ProductImages selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_images
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") ProductImages row, @Param("example") ProductImagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_images
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	int updateByExample(@Param("row") ProductImages row, @Param("example") ProductImagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_images
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	int updateByPrimaryKeySelective(ProductImages row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_images
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	int updateByPrimaryKey(ProductImages row);
}