package com.web.Agrifood.mapper;

import com.web.Agrifood.model.ProductCategory;
import com.web.Agrifood.model.ProductCategoryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProductCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	long countByExample(ProductCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	int deleteByExample(ProductCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	int insert(ProductCategory row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	int insertSelective(ProductCategory row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	List<ProductCategory> selectByExample(ProductCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	ProductCategory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") ProductCategory row, @Param("example") ProductCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	int updateByExample(@Param("row") ProductCategory row, @Param("example") ProductCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	int updateByPrimaryKeySelective(ProductCategory row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	int updateByPrimaryKey(ProductCategory row);
}