package com.web.Agrifood.mapper;

import com.web.Agrifood.model.Product;
import com.web.Agrifood.model.User;
import com.web.Agrifood.model.UserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import com.web.Agrifood.model.UserKey;
import com.web.Agrifood.model.UserWithBLOBs;
@Mapper
public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	long countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	
	int deleteByPrimaryKey(Integer id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	
	int insert(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	int insertSelective(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	
	User selectByPrimaryKey(Integer id);
	
	int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	int updateByExample(@Param("row") User row, @Param("example") UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */	
	int updateByPrimaryKeySelective(User row);
}