package com.web.Agrifood.model;

public class Cart {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cart.id
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cart.productId
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	private Integer productid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cart.userId
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cart.quantity
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	private Integer quantity;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cart.id
	 * @return  the value of cart.id
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cart.id
	 * @param id  the value for cart.id
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cart.productId
	 * @return  the value of cart.productId
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	public Integer getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cart.productId
	 * @param productid  the value for cart.productId
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cart.userId
	 * @return  the value of cart.userId
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cart.userId
	 * @param userid  the value for cart.userId
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cart.quantity
	 * @return  the value of cart.quantity
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cart.quantity
	 * @param quantity  the value for cart.quantity
	 * @mbg.generated  Wed Aug 24 01:09:07 ICT 2022
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
}