package com.web.Agrifood.model;

import java.util.Date;

public class CategoriesProducts {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.id
	 * @mbg.generated  Wed Aug 17 13:03:04 ICT 2022
	 */
	private Integer id;
	
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.title
	 * @mbg.generated  Wed Aug 17 13:03:04 ICT 2022
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.discount
	 * @mbg.generated  Wed Aug 17 13:03:04 ICT 2022
	 */
	private Float discount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.product_category
	 * @mbg.generated  Wed Aug 17 13:03:04 ICT 2022
	 */
	private Integer productCategory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.createAt
	 * @mbg.generated  Wed Aug 17 13:03:04 ICT 2022
	 */
	private Date createat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.updateAt
	 * @mbg.generated  Wed Aug 17 13:03:04 ICT 2022
	 */
	private Date updateat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.unit
	 * @mbg.generated  Wed Aug 17 13:03:04 ICT 2022
	 */
	private String unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.origin
	 * @mbg.generated  Wed Aug 17 13:03:04 ICT 2022
	 */
	private String origin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.preserve
	 * @mbg.generated  Wed Aug 17 13:03:04 ICT 2022
	 */
	private String preserve;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public Float getDiscount() {
		return discount;
	}
	public void setDiscount(Float discount) {
		this.discount = discount;
	}
	public Integer getProductCategory() {
		return productCategory;
	}
	public void setProductCategory(Integer productCategory) {
		this.productCategory = productCategory;
	}
	public Date getCreateat() {
		return createat;
	}
	public void setCreateat(Date createat) {
		this.createat = createat;
	}
	public Date getUpdateat() {
		return updateat;
	}
	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}
	public String getUnit() {
		return unit;
	}
	public void setUnit(String unit) {
		this.unit = unit;
	}
	public String getOrigin() {
		return origin;
	}
	public void setOrigin(String origin) {
		this.origin = origin;
	}
	public String getPreserve() {
		return preserve;
	}
	public void setPreserve(String preserve) {
		this.preserve = preserve;
	}
	public String getUserManual() {
		return userManual;
	}
	public void setUserManual(String userManual) {
		this.userManual = userManual;
	}
	public Integer getQuantity() {
		return quantity;
	}
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Integer getCategory_id() {
		return category_id;
	}
	public void setCategory_id(Integer category_id) {
		this.category_id = category_id;
	}
	public String getCategory_title() {
		return category_title;
	}
	public void setCategory_title(String category_title) {
		this.category_title = category_title;
	}
	public String getCategory_thumbnail() {
		return category_thumbnail;
	}
	public void setCategory_thumbnail(String category_thumbnail) {
		this.category_thumbnail = category_thumbnail;
	}
	public Float getPrice() {
		return price;
	}
	public void setPrice(Float price) {
		this.price = price;
	}
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.user_manual
	 * @mbg.generated  Wed Aug 17 13:03:04 ICT 2022
	 */
	private String userManual;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.quantity
	 * @mbg.generated  Wed Aug 17 13:03:04 ICT 2022
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.description
	 * @mbg.generated  Wed Aug 17 13:03:04 ICT 2022
	 */
	private String description;
	
	private Float price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.description
	 * @mbg.generated  Wed Aug 17 13:03:04 ICT 2022
	 */
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.id
	 * @mbg.generated  Sat Jul 16 08:46:16 ICT 2022
	 */
	private Integer category_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.title
	 * @mbg.generated  Sat Jul 16 08:46:16 ICT 2022
	 */
	private String category_title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.thumbnail
	 * @mbg.generated  Sat Jul 16 08:46:16 ICT 2022
	 */
	private String category_thumbnail;
}
