package com.web.Agrifood.model;

import java.util.Date;

public class Feedback extends FeedbackKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.date
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.rating
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    private Integer rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.feedbackcol
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    private String feedbackcol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.content
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.date
     *
     * @return the value of feedback.date
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.date
     *
     * @param date the value for feedback.date
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.rating
     *
     * @return the value of feedback.rating
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.rating
     *
     * @param rating the value for feedback.rating
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.feedbackcol
     *
     * @return the value of feedback.feedbackcol
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public String getFeedbackcol() {
        return feedbackcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.feedbackcol
     *
     * @param feedbackcol the value for feedback.feedbackcol
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public void setFeedbackcol(String feedbackcol) {
        this.feedbackcol = feedbackcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.content
     *
     * @return the value of feedback.content
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.content
     *
     * @param content the value for feedback.content
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public void setContent(String content) {
        this.content = content;
    }
}