package com.web.Agrifood.model;

public class FeedbackKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.userId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.productId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    private Integer productid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.userId
     *
     * @return the value of feedback.userId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.userId
     *
     * @param userid the value for feedback.userId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.productId
     *
     * @return the value of feedback.productId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.productId
     *
     * @param productid the value for feedback.productId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }
}