package com.web.Agrifood.model;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.orderId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.productId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.quantity
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.itemPrice
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    private Float itemprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.orderId
     *
     * @return the value of order_item.orderId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.orderId
     *
     * @param orderid the value for order_item.orderId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.productId
     *
     * @return the value of order_item.productId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.productId
     *
     * @param productid the value for order_item.productId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.quantity
     *
     * @return the value of order_item.quantity
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.quantity
     *
     * @param quantity the value for order_item.quantity
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.itemPrice
     *
     * @return the value of order_item.itemPrice
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public Float getItemprice() {
        return itemprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.itemPrice
     *
     * @param itemprice the value for order_item.itemPrice
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public void setItemprice(Float itemprice) {
        this.itemprice = itemprice;
    }
}