package com.web.Agrifood.model;

public class OrderStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_status.statusId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    private Integer statusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_status.description
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_status.statusId
     *
     * @return the value of order_status.statusId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public Integer getStatusid() {
        return statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_status.statusId
     *
     * @param statusid the value for order_status.statusId
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public void setStatusid(Integer statusid) {
        this.statusid = statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_status.description
     *
     * @return the value of order_status.description
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_status.description
     *
     * @param description the value for order_status.description
     *
     * @mbg.generated Thu Jul 14 09:56:16 ICT 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }
}