package com.web.Agrifood.model;

public class ProductWithBLOBs extends Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.description
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.information
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	private String information;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.description
	 * @return  the value of product.description
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.description
	 * @param description  the value for product.description
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.information
	 * @return  the value of product.information
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	public String getInformation() {
		return information;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.information
	 * @param information  the value for product.information
	 * @mbg.generated  Sun Aug 14 15:40:28 ICT 2022
	 */
	public void setInformation(String information) {
		this.information = information;
	}
}