package com.web.Agrifood.model;

import java.util.Date;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.id
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.title
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.discount
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	private Float discount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.product_category
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	private Integer productCategory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.createAt
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	private Date createat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.updateAt
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	private Date updateat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.unit
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	private String unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.origin
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	private String origin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.preserve
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	private String preserve;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.user_manual
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	private String userManual;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.quantity
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.price
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	private Float price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.description
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.id
	 * @return  the value of product.id
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.id
	 * @param id  the value for product.id
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.title
	 * @return  the value of product.title
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.title
	 * @param title  the value for product.title
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.discount
	 * @return  the value of product.discount
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public Float getDiscount() {
		return discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.discount
	 * @param discount  the value for product.discount
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public void setDiscount(Float discount) {
		this.discount = discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.product_category
	 * @return  the value of product.product_category
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public Integer getProductCategory() {
		return productCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.product_category
	 * @param productCategory  the value for product.product_category
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public void setProductCategory(Integer productCategory) {
		this.productCategory = productCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.createAt
	 * @return  the value of product.createAt
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public Date getCreateat() {
		return createat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.createAt
	 * @param createat  the value for product.createAt
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public void setCreateat(Date createat) {
		this.createat = createat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.updateAt
	 * @return  the value of product.updateAt
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public Date getUpdateat() {
		return updateat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.updateAt
	 * @param updateat  the value for product.updateAt
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.unit
	 * @return  the value of product.unit
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.unit
	 * @param unit  the value for product.unit
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.origin
	 * @return  the value of product.origin
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public String getOrigin() {
		return origin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.origin
	 * @param origin  the value for product.origin
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public void setOrigin(String origin) {
		this.origin = origin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.preserve
	 * @return  the value of product.preserve
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public String getPreserve() {
		return preserve;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.preserve
	 * @param preserve  the value for product.preserve
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public void setPreserve(String preserve) {
		this.preserve = preserve;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.user_manual
	 * @return  the value of product.user_manual
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public String getUserManual() {
		return userManual;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.user_manual
	 * @param userManual  the value for product.user_manual
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public void setUserManual(String userManual) {
		this.userManual = userManual;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.quantity
	 * @return  the value of product.quantity
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.quantity
	 * @param quantity  the value for product.quantity
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.price
	 * @return  the value of product.price
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public Float getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.price
	 * @param price  the value for product.price
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public void setPrice(Float price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.description
	 * @return  the value of product.description
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.description
	 * @param description  the value for product.description
	 * @mbg.generated  Mon Aug 22 15:49:51 ICT 2022
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}