package com.web.Agrifood.model;

public class ProductCategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_category.id
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_category.categoryId
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	private Integer categoryid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_category.title
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	private String title;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_category.id
	 * @return  the value of product_category.id
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_category.id
	 * @param id  the value for product_category.id
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_category.categoryId
	 * @return  the value of product_category.categoryId
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	public Integer getCategoryid() {
		return categoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_category.categoryId
	 * @param categoryid  the value for product_category.categoryId
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_category.title
	 * @return  the value of product_category.title
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_category.title
	 * @param title  the value for product_category.title
	 * @mbg.generated  Sat Jul 23 22:24:49 ICT 2022
	 */
	public void setTitle(String title) {
		this.title = title;
	}
}