package com.web.Agrifood.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.fullname
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.gender
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.address
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_at
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	private Date createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.status
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.permissionId
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	private Integer permissionid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.fullname
	 * @return  the value of user.fullname
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.fullname
	 * @param fullname  the value for user.fullname
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.gender
	 * @return  the value of user.gender
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.gender
	 * @param gender  the value for user.gender
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.address
	 * @return  the value of user.address
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.address
	 * @param address  the value for user.address
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.create_at
	 * @return  the value of user.create_at
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public Date getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.create_at
	 * @param createAt  the value for user.create_at
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.status
	 * @return  the value of user.status
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.status
	 * @param status  the value for user.status
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.permissionId
	 * @return  the value of user.permissionId
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public Integer getPermissionid() {
		return permissionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.permissionId
	 * @param permissionid  the value for user.permissionId
	 * @mbg.generated  Wed Sep 14 19:15:18 ICT 2022
	 */
	public void setPermissionid(Integer permissionid) {
		this.permissionid = permissionid;
	}
}